### ISSUE TITLE
Implement haversine

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/datapoint-python#10]
Within the function `_distance_between_coords` in the `Manager` object I initially implemented a haversine function for finding the nearest forecast site. However it didn't work properly and so I replaced it with a far simpler formula.

Despite this being more acurate than my original broken haversine function it probably isn't 100% correct. It should be replaced with a correct haversine function.

**Comment by EJEP** [comment]
What went wrong? I had a go implementing that function and it seems to work fine. See [distance_test.txt](https://github.com/jacobtomlinson/datapoint-python/files/2799460/distance_test.txt) for a comparison of distances calculated using the haversine formula and geopy. The method I used from geopy accounts for the fact that the earth is not quite spherical.

**Comment by EJEP** [comment]
If this is working properly, we could use this to limit forecasts to sites within some number of kilometers of the nearest site. This would solve the problem of requesting forecasts which are out of range.

**Comment by jacobtomlinson** [comment]
My Python was pretty poor when I wrote this library. So I was probably incompetence more than anything.

**Comment by EJEP** [comment]
Ok, I'll go ahead and merge the code once I've tried it up

**Comment by EJEP** [comment]
Fixed by #69
