### ISSUE TITLE
Clean up weather type results (night/day)

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/datapoint-python#18]
It seems that the API occasionally returns weather values which are specified as "night" or "day" (e.g "hail shower night" or "hail shower day") but at the wrong time of day. Usually around changeover times, it sometimes stays as night until around 9am, 3 hours after sunrise. And very occasionally returns a day value in the middle of the night.

I can imagine two solutions for this:

**A**) Calculate when sunrise/sunset is and just correct the values if they are wrong. 
_This remains inline with the API and just cleans the data_.

**B**) Strip the day/night from weather types completely (both "hail shower night" and "hail shower day" would just become "hail shower"). Then calculate day/night and store as a separate attribute. 
_Allows most flexibility when using the data_.

**Comment by EJEP** [comment]
I think stripping the day/night, calculating and storing separately is better. It seems strange that some types of weather (partly cloudy) have day/night given but others (cloudy) do not. Given the date and time is already stored for each timestep I'm not sure there's much point storing night/day at all.
