### ISSUE TITLE
Error with Python 2.7

### ISSUE THREAD

**Issue by springcoil** [jacobtomlinson/datapoint-python#22]
Hi I got this error when trying to reproduce one of the examples.
AttributeError                            Traceback (most recent call last)
<ipython-input-18-4a08bb81830a> in <module>()
----> 1 print now.weather.text

AttributeError: 'NoneType' object has no attribute 'weather'

**Comment by jacobtomlinson** [comment]
Hi, which example did you have this issue on? Can you comment with your code?

**Comment by springcoil** [comment]
Will do tomorrow

On Tue, Nov 17, 2015 at 9:02 PM, Jacob Tomlinson <notifications@github.com>
wrote:

> Hi, which example did you have this issue on? Can you comment with your
> code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacobtomlinson/datapoint-python/issues/22#issuecomment-157489248>
> .
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com

**Comment by jacobtomlinson** [comment]
@springcoil Any update on this?

**Comment by springcoil** [comment]
Hi Jacob,
I moved on and I can't reproduce the error sadly.

On Wed, Jan 6, 2016 at 5:19 PM, Jacob Tomlinson <notifications@github.com>
wrote:

> @springcoil <https://github.com/springcoil> Any update on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jacobtomlinson/datapoint-python/issues/22#issuecomment-169375661>
> .
>



-- 
Peadar Coyle
Skype: springcoilarch
www.twitter.com/springcoil
peadarcoyle.wordpress.com
