### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'weather'

### ISSUE THREAD

**Issue by rwassell** [jacobtomlinson/datapoint-python#27]
Hi,

Having updated the API key and location, I am running current_weather.py but get the following error:

Worthing (Beach)
Traceback (most recent call last):
  File "current_weather.py", line 21, in <module>
    print now.weather.text
AttributeError: 'bool' object has no attribute 'weather'

I then tried with:

current_timestep = forecast.now()
print current_timestep.weather.text

And that gives an error too:

Worthing (Beach)
Traceback (most recent call last):
  File "temp.py", line 22, in <module>
    print current_timestep.weather.text
AttributeError: 'bool' object has no attribute 'weather'

I've been investigating and can't work out what is wrong. I saw a recent bug due to the forecast.now problem but this seems to have been resolved and I do have the latest version. 

Any ideas what might be wrong?

Rob

**Comment by jacobtomlinson** [comment]
This has been fixed in #26 and will be included in the next release.
