### ISSUE TITLE
site.elevation returns County?

### ISSUE THREAD

**Issue by robmarkcole** [jacobtomlinson/datapoint-python#32]
![image](https://cloud.githubusercontent.com/assets/11855322/24906091/52d0647c-1eae-11e7-8fb2-c9a6dc88c772.png)

**Comment by robmarkcole** [comment]
Btw, could Pressure be added as an attribute?
Thanks :-)

**Comment by jacobtomlinson** [comment]
That's definitely wrong! Thanks for raising that, I'll take a look into it.

As for pressure i'm afraid the library can only return what the datapoint API provides, and pressure is not included.
http://www.metoffice.gov.uk/datapoint/product/uk-3hourly-site-specific-forecast

**Comment by robmarkcole** [comment]
Aha I see the problem. Perhaps http://www.metoffice.gov.uk/datapoint/product/uk-hourly-site-specific-observations ?

**Comment by jacobtomlinson** [comment]
Observations have not been implemented yet in this library (#4). I haven't got the time to do this at the moment.
