### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by fabaff** [jacobtomlinson/datapoint-python#36]
Please add timeout to all requests. Thanks.

**Comment by jacobtomlinson** [comment]
Thanks for raising this issue @fabaff. I will eneavour to take a look at this however I do not have much bandwidth for this project at the moment.

If you (or anyone else) would like to raise a Pull Request to add this feature I would be happy to review and merge it.

**Comment by EJEP** [comment]
This is added in the currently unmerged pull request #54, and will be included in version 0.5.0 which should be out in the next coupe of weeks

**Comment by EJEP** [comment]
Pull request #54 is now merged in to master, timeouts will be in version 0.5.0 which will be released soon.

**Comment by fabaff** [comment]
Thanks

**Comment by EJEP** [comment]
Version 0.6.0 is now on PyPi
