### ISSUE TITLE
Postcodes web service is dead, postcode example no longer works

### ISSUE THREAD

**Issue by EJEP** [jacobtomlinson/datapoint-python#45]
The web service used by the postcodes module is dead (see https://github.com/e-dard/postcodes/issues/5) so the postcodes example no longer works.

**Comment by jacobtomlinson** [comment]
Best to remove it then. Or find a new data source.

**Comment by EJEP** [comment]
I've switched to a different postcode API in 882a169a8758ca643af774c79b9b31951671e760
