### ISSUE TITLE
Remove python 2.6?

### ISSUE THREAD

**Issue by EJEP** [jacobtomlinson/datapoint-python#46]
Python 2.6 was end-of-lifed some time ago. @jacobtomlinson do you have any objections to removing it from the listed versions supported and from the tests? This probably ought to be done in a point release.

**Comment by jacobtomlinson** [comment]
I would prefer to leave support in for this if it's not causing too many problems  Just because I know it is being used by people who are stuck on RedHat/CentOS 6 which ships with 2.6.
