### ISSUE TITLE
Read the docs webhook

### ISSUE THREAD

**Issue by EJEP** [jacobtomlinson/datapoint-python#49]
@jacobtomlinson, setting up the webhook needs access to the settings page of the repository on GitHub, which I think only the owner has. From the readthedocs [documentation](https://docs.readthedocs.io/en/stable/webhooks.html#github) all that needs doing is copying the URL from the Admin->Integrations page on the read the docs settings to the GitHub integrations settings section and ticking a few boxes.

**Comment by EJEP** [comment]
Having tweaked an element of the documentation readthedocs did not rebuild automatically. The current webhook definitely doesn't work properly

**Comment by jacobtomlinson** [comment]
Ok I've added the webhook as per the documentation you mentioned.

**Comment by EJEP** [comment]
Thanks, hopefully it works

**Comment by EJEP** [comment]
This works now.
