### ISSUE TITLE
Convert documentation to ReStructured Text

### ISSUE THREAD

**Issue by EJEP** [jacobtomlinson/datapoint-python#52]
The documentation has quite a few tables in, which are written as html in the markdown files. These are rather hard to read. ReStructured Text has a built in table syntax which is easier to read. Changing this would not require changing the documentation text. It would require changing the documentation build system to use sphinx

**Comment by jacobtomlinson** [comment]
Happy with that.

**Comment by EJEP** [comment]
As an addendum to this the description in PyPi isn't being formatted properly.

**Comment by EJEP** [comment]
The documentation now uses .rst and sphinx
