### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by EJEP** [jacobtomlinson/datapoint-python#55]
@jacobtomlinson The observation code is now finished (pull request #53). Along with swapping longitude and latitude (pull request #31) and adding timeouts (a minor change in __call_api, pull request #54) there are probably enough changes to justify a bump in version number to 0.5.0, especially since #31 is not backwards compatible. What are your thoughts?

There are also some other things to do like: 

- ~~The PyPi page doesn't list python versions 3.5 and 3.6 which are tested by Travis.~~ This was correct in the master setup.py
- ~~The version of the requests module used in travis can be increased~~
- ~~python 3.7 could be tested against.~~
- ~~change longitude and latitude in observation code to ensure consistency~~
- ~~Add unit test for observation~~
- ~~Update object image in documentation to include observations~~

I will list anything else I think of over the next few days.

**Comment by jacobtomlinson** [comment]
Sounds good. Packaging and deployment to PyPI should be automated with Travis, so when a release is tagged on GitHub a release should trigger. Please feel free to go ahead with this when you are ready.

**Comment by EJEP** [comment]
Cool. I'll wait until I've had a look at the retrying with requests in case
it's easy to do and test

**Comment by EJEP** [comment]
Retrying the connection is likely to take a while, so it will be in a later version. Version 0.6.0 is now live
