### ISSUE TITLE
Security concerns in requests library

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/datapoint-python#60]
GitHub is raising security concerns with the versions of requests being used. It has suggested updating to `2.20.0` or above.

**Comment by EJEP** [comment]
I had been planning to leave the minimum version of requests for the install alone unless there are problems. I don't think datapoint requires anything new (but I've not finished testing the retry code yet).

Travis uses 2.21.0 for everything apart from python 2.6

**Comment by jacobtomlinson** [comment]
My concern is that there is a security issue with versions below `2.20.0`.

**Comment by EJEP** [comment]
Setting the minimum version to 2.20 shouldn't break anything (apart from python 2.6 support as you mentioned). I can increase the minimum version required in the next release, which will hopefully be done this weekend.

**Comment by jacobtomlinson** [comment]
How about this: we cut a release with the current version of the library. Then immediately upgrade the package to the latest version, drop support for Python 2 and remove any Python 2 compatibility code and cut another release. 

This leaves a version for Python 2 folks which is up to date and works. But then remove the headache of maintaining it. I've seen this happen in a few other projects I work on and it seems effective.

**Comment by EJEP** [comment]
Sounds good! With this in mind I propose the following course of action:

1. Finish observations documentation and merge into master.
2. Release version 0.5.0 without increasing the minimum version of requests required.
3. Remove python 2 compatibility code and increase the minimum version of requests to `2.20.0`.
4. Release version 0.6.0, explicitly dropping support for python 2.

How does that sound to you?

**Comment by EJEP** [comment]
If support is being removed, python 3.3 was end-of-lifed on 2017-09-29. I propose we also remove support for this version.

**Comment by jacobtomlinson** [comment]
Happy with that. Fine to drop 3.3 in 0.6.0 too.

**Comment by EJEP** [comment]
version 0.6.0 is now live, having followed the procedure in https://github.com/jacobtomlinson/datapoint-python/issues/60#issuecomment-457689835
