### ISSUE TITLE
Require point to be within a maximum distance of a forecast site

### ISSUE THREAD

**Issue by EJEP** [jacobtomlinson/datapoint-python#71]
Currently requesting data for coordinates which are outside the UK results in misleading data or no data (see #15, #37). Once haversine is implemented (issue #10, pull request #69) the distance from the requested location to the nearest site will be known in kilometres. The problem of the requested point being out of bounds would be solved by requiring that the point be within a set distance of the nearest forecast site. @jacobtomlinson do you have an idea of what a suitable distance would be?

**Comment by jacobtomlinson** [comment]
That's a good question. There might be something on the Met Office Datapoint website which suggests the range of the points.

**Comment by EJEP** [comment]
I haven't been able to find any information on what the range of the forecast from a site should be.

By drawing circles of constant radius around the points using cartopy, a radius of 30 km ensures that a forecast can be obtained for all of the UK. Actually all of the UK apart from the northern tip of Harris and a tiny bit of Northern Ireland are within 20km of a site. This image shows the UK overlaid with 30km circles centered on each site:
![tissot_30km](https://user-images.githubusercontent.com/22224469/52016593-e1ba5180-24dc-11e9-9047-d10d5d8ee29a.png)

And most locations are within 10 km of a site:
![tissot_10km](https://user-images.githubusercontent.com/22224469/52016610-f1399a80-24dc-11e9-8a12-38b88c4f982e.png)

With this in mind 30km seems like a reasonable way to go, although I would think the reliability of the forecast may be suspect at that distance.

**Comment by jacobtomlinson** [comment]
Looks reasonable to me!

**Comment by EJEP** [comment]
As a similar point, I will implement a similar limit for observations. For these, I think 20 km is acceptable as the radius to include all of the UK would be more than 50km. This map shows circles of 20 km around the observation sites:

![obs_tissot_20km](https://user-images.githubusercontent.com/22224469/52145210-4b129f80-2658-11e9-8d42-32ca1777e026.png)

**Comment by EJEP** [comment]
Once the distance limit for observations is in, I think it will be a good time to push version 0.7.0 to PyPI

**Comment by EJEP** [comment]
Limits are merged for both forecasts and observations
