### ISSUE TITLE
Version 0.7.0

### ISSUE THREAD

**Issue by EJEP** [jacobtomlinson/datapoint-python#78]
Renaming functions in #77 and limiting the distance of sites for responses (#74, #76) have the potential to break things. Along with some bug fixes, this seems like a good time to move to version 0.7.0

@jacobtomlinson what are your thoughts?

**Comment by EJEP** [comment]
@jacobtomlinson I will go ahead with this in the next couple of days unless you have any objections.

**Comment by jacobtomlinson** [comment]
👍
