### ISSUE TITLE
Versioned changelog

### ISSUE THREAD

**Issue by EJEP** [jacobtomlinson/datapoint-python#88]
There are tools which can help automate the change log between versions.This would be nice to have.

**Comment by EJEP** [comment]
Thinking on this some more, automation may not be ideal as anything using the git log will have a lot of noise in. A single, manually maintained file may be more convenient overall.

**Comment by jacobtomlinson** [comment]
If you intend on automating this process I would recommend some project workflow changes. Particularly insisting on a squash and merge for merging PRs. This keeps the git log nice and clean. 

Otherwise I would stick with a manual process.

**Comment by EJEP** [comment]
I'm leaning towards a manual process, in a single file which can be read by the setup.py and the documentation, I need to do some research to see how to go about this.

**Comment by EJEP** [comment]
My current thoughts are to store the changelog in separate file, probably `CHANGELOG.md` or similar, and either not include it in setup.py or extract the latest section and include it.

**Comment by EJEP** [comment]
Introduced in #93
