### ISSUE TITLE
Use semantic versioning?

### ISSUE THREAD

**Issue by EJEP** [jacobtomlinson/datapoint-python#95]
The version numbers currently follow x.y.z format. I think it would be a good idea to explicitly use semantic versioning as defined at https://semver.org/ to set version numbers. We are in 0.y.z so things are still fluid.

@jacobtomlinson what do you think?

**Comment by jacobtomlinson** [comment]
Yes. This repo should be following SemVer already. Perhaps we should explicitly state that in the README?
